basePath: /v1
definitions:
  models.Comments:
    properties:
      comment:
        type: string
      user:
        type: string
    type: object
  models.Posts:
    properties:
      _id:
        type: string
      comments:
        items:
          $ref: '#/definitions/models.Comments'
        type: array
      content:
        type: string
      dislikes:
        type: integer
      imageURL:
        type: string
      likes:
        type: integer
      user:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: Swagger Example API
  version: "1.0"
paths:
  /latest:
    get:
      description: get posts
      parameters:
      - description: apikey
        in: query
        name: apikey
        required: true
        type: string
      - description: offset
        in: query
        name: offset
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Posts'
            type: array
      summary: List Posts
swagger: "2.0"
